### ISSUE TITLE
Add fields

### ISSUE THREAD

**Issue by Shuricus** [Alintor/obsidian-kinopoisk-plugin#3]
It would be nice to add KinoPoisk and imdb ratings, the API seems to allow that.
If you put something like {rating} or {kp} in the template, it doesn't work

**Comment by Shuricus** [comment]
And also id of imdb

**Comment by Alintor** [comment]
New fields (ratingKp, ratingImdb, imdbId, tmdbId, kpHDId) added with version 1.0.2. Thanks for improvement request.

**Comment by Shuricus** [comment]
Plugin can't be updated

**Comment by Alintor** [comment]
Should be fine now

**Comment by Shuricus** [comment]
👌🏻
